version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DATABASE_URL=sqlite:///./data/intelligence.db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app

  # Note: Frontend is now a native Rust/Bevy application
  # Run with: cargo run
  # No Docker needed for the game frontend 