<script lang="ts">
  import { onMount } from 'svelte';
import { abilityManager } from '../services/AbilityManager';
import { selectedAgent, getAgentFullId } from '../services/CharacterManager';
import { skillTreeManager } from '../services/PerkManager';
import { settingsManager } from '../services/SettingsManager';
import { simpleFileReaderAbility, simpleFileWriterAbility } from '../abilities';

  let selectedFile: File | null = null;
  let fileContent = '';
  let testContent = '';
  let testFileName = 'test.txt';
  let testFileType = 'text';
  let readResult: any = null;
  let writeResult: any = null;
  let hasFileReader = false;
  let hasFileWriter = false;

  // Reactive statement to check abilities
  $: if ($selectedAgent) {
    const agentId = getAgentFullId($selectedAgent);
    hasFileReader = abilityManager.hasAbility(agentId, 'read_files');
    hasFileWriter = abilityManager.hasAbility(agentId, 'write_files');
    
    // Debug logging
    console.log('🔍 Agent abilities check:', {
      agentId,
      hasFileReader,
      hasFileWriter,
      selectedAgent: $selectedAgent
    });
  }

  function handleFileSelect(event: Event) {
    const target = event.target as HTMLInputElement;
    if (target.files && target.files.length > 0) {
      selectedFile = target.files[0];
      console.log('📁 Selected file:', selectedFile.name, selectedFile.size, 'bytes');
    }
  }

  async function testFileRead() {
    if (!selectedFile || !$selectedAgent) return;

    const agentId = getAgentFullId($selectedAgent);
    
    try {
      console.log('🔍 Testing file read for agent:', agentId);
      console.log('📁 File:', selectedFile.name, selectedFile.size, 'bytes');
      
      // Check if ability is available
      const ability = abilityManager.getAbility('read_files');
      console.log('🔍 Read ability available:', !!ability);
      
      // Check if agent has the ability
      const hasAbility = abilityManager.hasAbility(agentId, 'read_files');
      console.log('🔍 Agent has read ability:', hasAbility);
      
      const result = await abilityManager.executeAbility(agentId, 'read_files', {
        file: selectedFile
      });
      
      readResult = result;
      fileContent = result.content || '';
      
      console.log('✅ File read result:', result);
      
      if (result.success) {
        alert(`✅ File read successfully!\nFile: ${result.fileName}\nSize: ${result.fileSize} bytes\nContent length: ${result.content?.length || 0} characters`);
      } else {
        alert(`❌ File read failed: ${result.error}`);
      }
    } catch (error) {
      console.error('❌ Error testing file read:', error);
      alert(`❌ Error: ${error}`);
    }
  }

  async function testFileWrite() {
    if (!testContent || !$selectedAgent) return;

    const agentId = getAgentFullId($selectedAgent);
    
    try {
      console.log('✍️ Testing file write for agent:', agentId);
      console.log('📝 Content length:', testContent.length, 'characters');
      
      const result = await abilityManager.executeAbility(agentId, 'write_files', {
        content: testContent,
        fileName: testFileName,
        fileType: testFileType
      });
      
      writeResult = result;
      
      console.log('✅ File write result:', result);
      
      if (result.success) {
        alert(`✅ File written successfully!\nFile: ${result.fileName}\nSize: ${result.fileSize} bytes\nDownload URL: ${result.downloadUrl}`);
      } else {
        alert(`❌ File write failed: ${result.error}`);
      }
    } catch (error) {
      console.error('❌ Error testing file write:', error);
      alert(`❌ Error: ${error}`);
    }
  }

  function grantFileAbilities() {
    if (!$selectedAgent) return;
    
    const agentId = getAgentFullId($selectedAgent);
    abilityManager.grantAbility(agentId, 'read_files');
    abilityManager.grantAbility(agentId, 'write_files');
    
    console.log('✅ Granted file abilities to agent:', agentId);
    alert('✅ File abilities granted to agent!');
  }

  function createTestContent() {
    testContent = `# Test File Content

This is a test file generated by the AI agent system.

## Features
- File reading and writing capabilities
- Support for various text file formats
- Automatic file download functionality

## File Information
- Generated: ${new Date().toISOString()}
- Agent: ${$selectedAgent || 'Unknown'}
- Content Type: ${testFileType}

## Sample Data
Here's some sample data to test the file writing functionality:

\`\`\`json
{
  "test": true,
  "message": "Hello from the AI agent!",
  "timestamp": "${new Date().toISOString()}",
  "agent": "${$selectedAgent || 'Unknown'}"
}
\`\`\`

This content demonstrates the file writing capabilities of the system.`;
  }

  onMount(() => {
    // Grant file abilities to all agents for testing
    const agents = ['agent_alpha', 'agent_beta', 'agent_gamma'];
    agents.forEach(agentId => {
      abilityManager.grantAbility(agentId, 'read_files');
      abilityManager.grantAbility(agentId, 'write_files');
    });
    
    console.log('✅ File abilities granted to all agents for testing');
    
    // Debug: Check if abilities are registered
    const allAbilities = abilityManager.getAllAbilities();
    console.log('🔍 All registered abilities:', allAbilities.map(a => a.id));
    
    // Debug: Check if file abilities are available
    const fileReader = abilityManager.getAbility('read_files');
    const fileWriter = abilityManager.getAbility('write_files');
    console.log('🔍 File reader available:', !!fileReader);
    console.log('🔍 File writer available:', !!fileWriter);
  });
</script>

<div class="file-ability-tester">
  <h3>📁 File Ability Tester</h3>
  
  <!-- File Reading Test -->
  <div class="tester-section">
    <h4>📖 File Reading Test</h4>
          <div class="file-input">
        <label>Select a text file to read:</label>
        <input type="file" accept=".txt,.js,.ts,.html,.css,.json,.md" on:change={handleFileSelect} />
        <span>{selectedFile ? selectedFile.name : 'No file chosen'}</span>
      </div>
    <button class="btn-primary" disabled={!selectedFile} on:click={testFileRead}>
      🔍 Test File Read {hasFileReader ? '(✅)' : '(❌)'}
    </button>
    {#if readResult}
      <div class="result">
        <h5>Read Result:</h5>
        <div class="file-info">
          <p><strong>File:</strong> {readResult.fileName}</p>
          <p><strong>Size:</strong> {readResult.fileSize} bytes</p>
          <p><strong>Success:</strong> {readResult.success ? '✅' : '❌'}</p>
          {#if readResult.error}
            <p><strong>Error:</strong> {readResult.error}</p>
          {/if}
        </div>
        {#if readResult.content}
          <div class="file-content">
            <h6>File Content:</h6>
            <pre class="content-display">{readResult.content}</pre>
          </div>
        {/if}
      </div>
    {/if}
  </div>

  <!-- File Writing Test -->
  <div class="tester-section">
    <h4>✏️ File Writing Test</h4>
          <div class="content-input">
        <label>File Name:</label>
        <input type="text" bind:value={testFileName} placeholder="test.txt" />
      </div>
      <div class="content-input">
        <label>File Type:</label>
        <select bind:value={testFileType}>
          <option value="text">Text (.txt)</option>
          <option value="markdown">Markdown (.md)</option>
          <option value="json">JSON (.json)</option>
          <option value="javascript">JavaScript (.js)</option>
          <option value="typescript">TypeScript (.ts)</option>
          <option value="html">HTML (.html)</option>
          <option value="css">CSS (.css)</option>
        </select>
      </div>
      <div class="content-input">
        <label>Content to Write:</label>
        <textarea bind:value={testContent} placeholder="Enter content to write to file..." rows="6"></textarea>
      </div>
      <div class="button-group">
        <button class="btn-secondary" on:click={createTestContent}>
          📄 Generate Test Content
        </button>
        <button class="btn-primary" disabled={!testContent.trim()} on:click={testFileWrite}>
          ✏️ Test File Write {hasFileWriter ? '(✅)' : '(❌)'}
        </button>
      </div>
    {#if writeResult}
      <div class="result">
        <h5>Write Result:</h5>
        <div class="file-info">
          <p><strong>File:</strong> {writeResult.fileName}</p>
          <p><strong>Size:</strong> {writeResult.fileSize} bytes</p>
          <p><strong>Success:</strong> {writeResult.success ? '✅' : '❌'}</p>
          {#if writeResult.error}
            <p><strong>Error:</strong> {writeResult.error}</p>
          {/if}
          {#if writeResult.downloadUrl}
            <p><strong>Download:</strong> <a href={writeResult.downloadUrl} download={writeResult.fileName} class="download-link">📥 Download File</a></p>
          {/if}
        </div>
      </div>
    {/if}
  </div>

  <!-- Ability Status -->
  <div class="tester-section">
    <h4>⚙️ Ability Status</h4>
    <p><strong>Current Agent:</strong> {$selectedAgent || 'None'}</p>
    <p><strong>File Reader:</strong> {hasFileReader ? '✅ Granted' : '❌ Not Granted'}</p>
    <p><strong>File Writer:</strong> {hasFileWriter ? '✅ Granted' : '❌ Not Granted'}</p>
    <p class="note">💡 Enable/disable file abilities using the skill panel switches above.</p>
    
    <button class="btn-secondary" on:click={() => {
      // Check if abilities are registered
      const allAbilities = abilityManager.getAllAbilities();
      const readAbility = abilityManager.getAbility('read_files');
      const writeAbility = abilityManager.getAbility('write_files');
      
      console.log('🔍 All abilities:', allAbilities.map(a => a.id));
      console.log('🔍 Read ability:', readAbility);
      console.log('🔍 Write ability:', writeAbility);
      
      alert(`🔍 Ability Check:\nAll: ${allAbilities.map(a => a.id).join(', ')}\nRead: ${readAbility ? '✅' : '❌'}\nWrite: ${writeAbility ? '✅' : '❌'}`);
    }}>
      🔍 Check Abilities
    </button>
    
    <button class="btn-secondary" on:click={() => {
      // Manually grant abilities to test
      if ($selectedAgent) {
        const agentId = getAgentFullId($selectedAgent);
        abilityManager.grantAbility(agentId, 'read_files');
        abilityManager.grantAbility(agentId, 'write_files');
        
        // Check if they were granted
        const hasRead = abilityManager.hasAbility(agentId, 'read_files');
        const hasWrite = abilityManager.hasAbility(agentId, 'write_files');
        
        alert(`🔧 Manual Grant Test:\nRead: ${hasRead ? '✅' : '❌'}\nWrite: ${hasWrite ? '✅' : '❌'}`);
      }
    }}>
      🔧 Test Grant
    </button>
  </div>
</div>

<style>
  .file-ability-tester {
    padding: 20px;
    background: rgba(0, 0, 0, 0.3);
    border-radius: 8px;
    margin: 10px 0;
  }

  .file-ability-tester h3 {
    margin: 0 0 20px 0;
    color: #00ff88;
  }

  .tester-section {
    margin-bottom: 30px;
    padding: 20px;
    background: rgba(0, 0, 0, 0.2);
    border-radius: 6px;
    border: 1px solid rgba(0, 255, 136, 0.2);
  }

  .tester-section h4 {
    margin: 0 0 15px 0;
    color: #00ff88;
  }

  .file-input,
  .content-input {
    margin-bottom: 15px;
  }

  .file-input label,
  .content-input label {
    display: block;
    margin-bottom: 5px;
    color: rgba(255, 255, 255, 0.8);
    font-weight: bold;
  }

  .file-input input,
  .content-input input,
  .content-input select,
  .content-input textarea {
    width: 100%;
    padding: 8px;
    border: 1px solid rgba(0, 255, 136, 0.3);
    border-radius: 4px;
    background: rgba(0, 0, 0, 0.5);
    color: white;
    font-size: 14px;
  }

  .content-input textarea {
    resize: vertical;
    min-height: 100px;
  }

  .file-info {
    background: rgba(0, 255, 136, 0.1);
    padding: 10px;
    border-radius: 4px;
    margin-bottom: 15px;
  }

  .file-info p {
    margin: 5px 0;
    color: rgba(255, 255, 255, 0.8);
  }

  .test-actions {
    display: flex;
    gap: 10px;
    margin-bottom: 15px;
  }

  .result-section {
    background: rgba(0, 0, 0, 0.3);
    padding: 15px;
    border-radius: 4px;
    margin-top: 15px;
  }

  .result-section h5 {
    margin: 0 0 10px 0;
    color: #00ff88;
  }

  .result-section pre {
    background: rgba(0, 0, 0, 0.5);
    padding: 10px;
    border-radius: 4px;
    overflow-x: auto;
    font-size: 12px;
    color: rgba(255, 255, 255, 0.8);
  }

  .content-preview {
    margin-top: 15px;
  }

  .content-preview h6 {
    margin: 0 0 10px 0;
    color: #00ff88;
  }

  .content-preview textarea {
    width: 100%;
    height: 200px;
    background: rgba(0, 0, 0, 0.5);
    border: 1px solid rgba(0, 255, 136, 0.3);
    border-radius: 4px;
    color: white;
    font-family: monospace;
    font-size: 12px;
    resize: vertical;
  }

  .ability-status {
    background: rgba(0, 255, 136, 0.1);
    padding: 15px;
    border-radius: 4px;
    margin-bottom: 15px;
  }

  .ability-status p {
    margin: 5px 0;
    color: rgba(255, 255, 255, 0.8);
  }

  .btn-primary,
  .btn-secondary {
    padding: 8px 16px;
    border: 1px solid rgba(0, 255, 136, 0.3);
    border-radius: 4px;
    background: transparent;
    color: rgba(255, 255, 255, 0.8);
    cursor: pointer;
    transition: all 0.2s ease;
  }

  .btn-primary {
    background: rgba(0, 255, 136, 0.1);
    color: #00ff88;
  }

  .btn-primary:hover:not(:disabled) {
    background: rgba(0, 255, 136, 0.2);
  }

  .btn-secondary:hover:not(:disabled) {
    background: rgba(0, 255, 136, 0.1);
    color: #00ff88;
  }

  .btn-primary:disabled,
  .btn-secondary:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .file-info {
    background: rgba(0, 0, 0, 0.3);
    padding: 10px;
    border-radius: 4px;
    margin-bottom: 10px;
  }

  .file-info p {
    margin: 3px 0;
    font-size: 0.9rem;
  }

  .file-content {
    margin-top: 15px;
  }

  .file-content h6 {
    margin: 0 0 10px 0;
    color: #00ff88;
    font-size: 0.9rem;
  }

  .content-display {
    background: rgba(0, 0, 0, 0.5);
    padding: 15px;
    border-radius: 4px;
    border: 1px solid rgba(0, 255, 136, 0.2);
    overflow-x: auto;
    font-family: 'Courier New', monospace;
    font-size: 12px;
    line-height: 1.4;
    color: rgba(255, 255, 255, 0.9);
    max-height: 300px;
    overflow-y: auto;
    white-space: pre-wrap;
    word-wrap: break-word;
  }

  .download-link {
    color: #00ff88;
    text-decoration: none;
    padding: 4px 8px;
    background: rgba(0, 255, 136, 0.1);
    border-radius: 4px;
    border: 1px solid rgba(0, 255, 136, 0.3);
    transition: all 0.2s ease;
  }

  .download-link:hover {
    background: rgba(0, 255, 136, 0.2);
    color: #00ff88;
  }
</style> 